-- ArbiScan mock product seed
-- Run this once in Supabase SQL Editor after 002_product_source_data.sql.

insert into products (canonical_key, title, category, source_data)
values
('prod-walmart-dyson','다이슨 V8 오리진 무선청소기 (Dyson V8 Origin Cordless Vacuum)','가전 · 디지털','{"id":"prod-walmart-dyson","asin":"US-AMZN-B08H7341G3","sourceMarket":"US-AMZN","sourceCurrency":"USD","sourcePrice":299,"targetSellingKrw":499000,"naverLowestKrw":519000,"weightKg":3.2,"roiPercent":8.9,"netProfitKrw":38500,"riskLevel":"low","isWatchlisted":true,"stockCount":28,"matchScore":99.8,"condition":"BRAND_NEW"}'),
('prod-target-stanley','스탠리 퀜처 H2.0 플로우스테이트 텀블러 40oz (Stanley Quencher H2.0 40oz)','주방용품 · 리빙','{"id":"prod-target-stanley","asin":"US-AMZN-B0BNL2N7F2","sourceMarket":"US-AMZN","sourceCurrency":"USD","sourcePrice":45,"targetSellingKrw":89000,"naverLowestKrw":94000,"weightKg":0.65,"roiPercent":11.3,"netProfitKrw":8500,"riskLevel":"very_low","isWatchlisted":true,"stockCount":65,"matchScore":99.9,"condition":"BRAND_NEW"}'),
('prod-ebay-bose','보스 콰이어트컴포트 울트라 헤드폰 (Bose QuietComfort Ultra Headphones)','오디오 · 음향기기','{"id":"prod-ebay-bose","asin":"US-AMZN-B0CCZ26B5V","sourceMarket":"US-AMZN","sourceCurrency":"USD","sourcePrice":349,"targetSellingKrw":559000,"naverLowestKrw":579000,"weightKg":0.95,"roiPercent":5.8,"netProfitKrw":28700,"riskLevel":"low","isWatchlisted":false,"stockCount":20,"matchScore":99.6,"condition":"BRAND_NEW"}'),
('prod-walmart-lego','레고 스타워즈 밀레니엄 팔콘 75257 (LEGO Star Wars Millennium Falcon 75257)','키덜트 · 완구','{"id":"prod-walmart-lego","asin":"US-AMZN-B07NDY9T69","sourceMarket":"US-AMZN","sourceCurrency":"USD","sourcePrice":169.99,"targetSellingKrw":295000,"naverLowestKrw":309000,"weightKg":2.1,"roiPercent":9.9,"netProfitKrw":25000,"riskLevel":"very_low","isWatchlisted":false,"stockCount":34,"matchScore":99.5,"condition":"BRAND_NEW"}'),
('prod-target-kitchenaid','키친에이드 아티잔 미니 3.5쿼터 스탠드 믹서 (KitchenAid Artisan Mini 3.5Qt)','주방가전 · 제과제빵','{"id":"prod-target-kitchenaid","asin":"US-AMZN-B01DKR4V8U","sourceMarket":"US-AMZN","sourceCurrency":"USD","sourcePrice":349.99,"targetSellingKrw":619000,"naverLowestKrw":649000,"weightKg":6.8,"roiPercent":15.1,"netProfitKrw":76400,"riskLevel":"amber","isWatchlisted":false,"stockCount":14,"matchScore":99.1,"condition":"BRAND_NEW"}'),
('prod-ebay-supreme','슈프림 박스로고 크루넥 맨투맨 (Supreme Box Logo Crewneck Sweatshirt)','패션 · 스트릿웨어','{"id":"prod-ebay-supreme","asin":"US-AMZN-B0CKTR6K5H","sourceMarket":"US-AMZN","sourceCurrency":"USD","sourcePrice":275,"targetSellingKrw":469000,"naverLowestKrw":489000,"weightKg":0.8,"roiPercent":11.8,"netProfitKrw":46500,"riskLevel":"very_low","isWatchlisted":true,"stockCount":16,"matchScore":99.4,"condition":"BRAND_NEW"}'),
('prod-turntable','오디오테크니카 AT-LP60X 입문용 턴테이블 (Audio-Technica AT-LP60X)','오디오 · 음향기기','{"id":"prod-turntable","asin":"JP-AMZN-B07N3XJ66N","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":17818,"targetSellingKrw":235000,"naverLowestKrw":249000,"weightKg":1.8,"roiPercent":23,"netProfitKrw":41400,"riskLevel":"amber","isWatchlisted":false,"stockCount":18,"matchScore":99.7,"condition":"BRAND_NEW"}'),
('prod-sony-headphones','소니 노이즈캔슬링 무선 헤드폰 WH-1000XM5 (Sony WH-1000XM5)','디지털 · 모바일','{"id":"prod-sony-headphones","asin":"JP-AMZN-B09Z2S9FSX","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":33637,"targetSellingKrw":399000,"naverLowestKrw":429000,"weightKg":0.9,"roiPercent":17,"netProfitKrw":54600,"riskLevel":"low","isWatchlisted":true,"stockCount":54,"matchScore":99.8,"condition":"BRAND_NEW"}'),
('prod-snowpeak-mug','스노우피크 티타늄 싱글머그 450 (Snow Peak MG-143 Titanium Mug)','캠핑 · 아웃도어','{"id":"prod-snowpeak-mug","asin":"JP-AMZN-B06XX4G5XT","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":3520,"targetSellingKrw":54000,"naverLowestKrw":59000,"weightKg":0.3,"roiPercent":12.9,"netProfitKrw":5800,"riskLevel":"very_low","isWatchlisted":true,"stockCount":42,"matchScore":99.9,"condition":"BRAND_NEW"}'),
('prod-switch-oled','닌텐도 스위치 OLED 모델 화이트 (Nintendo Switch OLED Model White)','게임 · 완구','{"id":"prod-switch-oled","asin":"JP-AMZN-B098B8PFXY","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":37980,"targetSellingKrw":415000,"naverLowestKrw":428000,"weightKg":1.5,"roiPercent":8.3,"netProfitKrw":30100,"riskLevel":"amber","isWatchlisted":false,"stockCount":12,"matchScore":99.2,"condition":"BRAND_NEW"}'),
('prod-braun-shaver','브라운 시리즈9 PRO 전기면도기 (Braun Series 9 Pro Electric Shaver)','생활 · 뷰티가전','{"id":"prod-braun-shaver","asin":"US-AMZN-B099TCPMQ5","sourceMarket":"US-AMZN","sourceCurrency":"USD","sourcePrice":249.99,"targetSellingKrw":429000,"naverLowestKrw":449000,"weightKg":1.2,"roiPercent":12,"netProfitKrw":43400,"riskLevel":"low","isWatchlisted":true,"stockCount":22,"matchScore":99.4,"condition":"BRAND_NEW"}'),
('prod-kyocera-knives','교세라 세라믹 주방칼 FKR-140 (Kyocera Ceramic Santoku Knife 14cm)','주방용품','{"id":"prod-kyocera-knives","asin":"JP-AMZN-B0029XG0EI","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":4280,"targetSellingKrw":64000,"naverLowestKrw":69000,"weightKg":0.5,"roiPercent":16,"netProfitKrw":8300,"riskLevel":"low","isWatchlisted":true,"stockCount":35,"matchScore":99.8,"condition":"BRAND_NEW"}'),
('prod-logitech-mx','로지텍 MX Master 3S 무선 마우스 (Logitech MX Master 3S Wireless Mouse)','디지털 · 주변기기','{"id":"prod-logitech-mx","asin":"US-AMZN-B0B11LJ69K","sourceMarket":"US-AMZN","sourceCurrency":"USD","sourcePrice":99.99,"targetSellingKrw":169000,"naverLowestKrw":179000,"weightKg":0.4,"roiPercent":5.1,"netProfitKrw":7700,"riskLevel":"low","isWatchlisted":true,"stockCount":48,"matchScore":99.7,"condition":"BRAND_NEW"}'),
('prod-rakuten-skii','SK-II 페이셜 트리트먼트 피테라 에센스 230ml (SK-II Facial Treatment Essence)','뷰티 · 화장품','{"id":"prod-rakuten-skii","asin":"JP-AMZN-B00V4L7J52","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":24800,"targetSellingKrw":295000,"naverLowestKrw":309000,"weightKg":0.6,"roiPercent":15.5,"netProfitKrw":37200,"riskLevel":"low","isWatchlisted":true,"stockCount":30,"matchScore":99.6,"condition":"BRAND_NEW"}'),
('prod-yahoo-anello','아넬로 클래식 방수 백팩 (anello Classic Water-Repellent Backpack AT-B0193A)','패션 · 잡화','{"id":"prod-yahoo-anello","asin":"JP-AMZN-B016XMT4Y2","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":4950,"targetSellingKrw":79000,"naverLowestKrw":84000,"weightKg":0.5,"roiPercent":28,"netProfitKrw":16300,"riskLevel":"very_low","isWatchlisted":false,"stockCount":40,"matchScore":99.3,"condition":"BRAND_NEW"}'),
('prod-tiger-bottle','타이거 스테인리스 보온보냉병 500ml (Tiger MMZ-K050 Thermal Bottle)','생활 · 주방용품','{"id":"prod-tiger-bottle","asin":"JP-AMZN-B099KTN527","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":2780,"targetSellingKrw":45000,"naverLowestKrw":49000,"weightKg":0.6,"roiPercent":10.4,"netProfitKrw":4000,"riskLevel":"very_low","isWatchlisted":false,"stockCount":60,"matchScore":99.4,"condition":"BRAND_NEW"}'),
('prod-porter-bag','요시다 포터 탱커 숄더백 (Yoshida Porter Tanker Shoulder Bag 622-76991)','패션 · 잡화','{"id":"prod-porter-bag","asin":"JP-AMZN-B07P8NLYB3","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":22000,"targetSellingKrw":329000,"naverLowestKrw":349000,"weightKg":0.5,"roiPercent":44.1,"netProfitKrw":94800,"riskLevel":"low","isWatchlisted":false,"stockCount":15,"matchScore":99.1,"condition":"BRAND_NEW"}'),
('prod-delonghi-dedica','드롱기 데디카 메탈릭 에스프레소 머신 EC680 (DeLonghi Dedica EC680)','생활 · 커피가전','{"id":"prod-delonghi-dedica","asin":"JP-AMZN-B00V33V1O4","sourceMarket":"JP-AMZN","sourceCurrency":"JPY","sourcePrice":27800,"targetSellingKrw":379000,"naverLowestKrw":399000,"weightKg":4.2,"roiPercent":31.7,"netProfitKrw":86000,"riskLevel":"amber","isWatchlisted":false,"stockCount":11,"matchScore":99.2,"condition":"BRAND_NEW"}')
on conflict (canonical_key) do update
set title=excluded.title,
    category=excluded.category,
    source_data=excluded.source_data,
    updated_at=now();
